//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyczarTool {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localized {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localized() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("KeyczarTool.Localized", typeof(Localized).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AddKey {
            get {
                return ResourceManager.GetString("AddKey", resourceCulture);
            }
        }
        
        internal static string Asymmetric {
            get {
                return ResourceManager.GetString("Asymmetric", resourceCulture);
            }
        }
        
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        internal static string Crypter {
            get {
                return ResourceManager.GetString("Crypter", resourceCulture);
            }
        }
        
        internal static string Demote {
            get {
                return ResourceManager.GetString("Demote", resourceCulture);
            }
        }
        
        internal static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        internal static string ImportKey {
            get {
                return ResourceManager.GetString("ImportKey", resourceCulture);
            }
        }
        
        internal static string ImportLocation {
            get {
                return ResourceManager.GetString("ImportLocation", resourceCulture);
            }
        }
        
        internal static string ImportPassword {
            get {
                return ResourceManager.GetString("ImportPassword", resourceCulture);
            }
        }
        
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        internal static string MsgCouldNotWrite {
            get {
                return ResourceManager.GetString("MsgCouldNotWrite", resourceCulture);
            }
        }
        
        internal static string MsgCreatedKey {
            get {
                return ResourceManager.GetString("MsgCreatedKey", resourceCulture);
            }
        }
        
        internal static string MsgCreatedKeySet {
            get {
                return ResourceManager.GetString("MsgCreatedKeySet", resourceCulture);
            }
        }
        
        internal static string MsgDemotedVersion {
            get {
                return ResourceManager.GetString("MsgDemotedVersion", resourceCulture);
            }
        }
        
        internal static string MsgExistingKeySet {
            get {
                return ResourceManager.GetString("MsgExistingKeySet", resourceCulture);
            }
        }
        
        internal static string MsgExportedPem {
            get {
                return ResourceManager.GetString("MsgExportedPem", resourceCulture);
            }
        }
        
        internal static string MsgInvalidStatus {
            get {
                return ResourceManager.GetString("MsgInvalidStatus", resourceCulture);
            }
        }
        
        internal static string MsgUnknownVersion {
            get {
                return ResourceManager.GetString("MsgUnknownVersion", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string Padding {
            get {
                return ResourceManager.GetString("Padding", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string Purpose {
            get {
                return ResourceManager.GetString("Purpose", resourceCulture);
            }
        }
        
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        internal static string UnofficialCreate {
            get {
                return ResourceManager.GetString("UnofficialCreate", resourceCulture);
            }
        }
        
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        internal static string MsgForKeySet {
            get {
                return ResourceManager.GetString("MsgForKeySet", resourceCulture);
            }
        }
        
        internal static string MsgForImport {
            get {
                return ResourceManager.GetString("MsgForImport", resourceCulture);
            }
        }
        
        internal static string MsgUnparsableImport {
            get {
                return ResourceManager.GetString("MsgUnparsableImport", resourceCulture);
            }
        }
        
        internal static string MsgConflictingKeyTypes {
            get {
                return ResourceManager.GetString("MsgConflictingKeyTypes", resourceCulture);
            }
        }
        
        internal static string MsgImportedNewKey {
            get {
                return ResourceManager.GetString("MsgImportedNewKey", resourceCulture);
            }
        }
        
        internal static string MsgNewPublicKeySet {
            get {
                return ResourceManager.GetString("MsgNewPublicKeySet", resourceCulture);
            }
        }
        
        internal static string Promote {
            get {
                return ResourceManager.GetString("Promote", resourceCulture);
            }
        }
        
        internal static string PubKey {
            get {
                return ResourceManager.GetString("PubKey", resourceCulture);
            }
        }
        
        internal static string MsgPromotedVersion {
            get {
                return ResourceManager.GetString("MsgPromotedVersion", resourceCulture);
            }
        }
        
        internal static string Revoke {
            get {
                return ResourceManager.GetString("Revoke", resourceCulture);
            }
        }
        
        internal static string MsgRevokedVersion {
            get {
                return ResourceManager.GetString("MsgRevokedVersion", resourceCulture);
            }
        }
        
        internal static string MsgCouldNotRevoke {
            get {
                return ResourceManager.GetString("MsgCouldNotRevoke", resourceCulture);
            }
        }
        
        internal static string MsgUnknownCompression {
            get {
                return ResourceManager.GetString("MsgUnknownCompression", resourceCulture);
            }
        }
        
        internal static string UseKey {
            get {
                return ResourceManager.GetString("UseKey", resourceCulture);
            }
        }
        
        internal static string Binary {
            get {
                return ResourceManager.GetString("Binary", resourceCulture);
            }
        }
        
        internal static string Compression {
            get {
                return ResourceManager.GetString("Compression", resourceCulture);
            }
        }
        
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        internal static string MsgPleaseEnterPassword {
            get {
                return ResourceManager.GetString("MsgPleaseEnterPassword", resourceCulture);
            }
        }
        
        internal static string MsgPleaseReenterPassword {
            get {
                return ResourceManager.GetString("MsgPleaseReenterPassword", resourceCulture);
            }
        }
        
        internal static string MsgPasswordDidNotMatch {
            get {
                return ResourceManager.GetString("MsgPasswordDidNotMatch", resourceCulture);
            }
        }
        
        internal static string MsgPasswordGiveUp {
            get {
                return ResourceManager.GetString("MsgPasswordGiveUp", resourceCulture);
            }
        }
        
        internal static string MsgMessageFlagWithPassword {
            get {
                return ResourceManager.GetString("MsgMessageFlagWithPassword", resourceCulture);
            }
        }
        
        internal static string MsgForExport {
            get {
                return ResourceManager.GetString("MsgForExport", resourceCulture);
            }
        }
        
        internal static string PasswordCommand {
            get {
                return ResourceManager.GetString("PasswordCommand", resourceCulture);
            }
        }
        
        internal static string MsgRemovedPassword {
            get {
                return ResourceManager.GetString("MsgRemovedPassword", resourceCulture);
            }
        }
        
        internal static string PasswordPromptOldPassword {
            get {
                return ResourceManager.GetString("PasswordPromptOldPassword", resourceCulture);
            }
        }
        
        internal static string PasswordPromptNewPassword {
            get {
                return ResourceManager.GetString("PasswordPromptNewPassword", resourceCulture);
            }
        }
        
        internal static string MsgAddedPasssword {
            get {
                return ResourceManager.GetString("MsgAddedPasssword", resourceCulture);
            }
        }
        
        internal static string MsgChangedPassword {
            get {
                return ResourceManager.GetString("MsgChangedPassword", resourceCulture);
            }
        }
        
        internal static string Crypter2 {
            get {
                return ResourceManager.GetString("Crypter2", resourceCulture);
            }
        }
        
        internal static string Destination2 {
            get {
                return ResourceManager.GetString("Destination2", resourceCulture);
            }
        }
        
        internal static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        internal static string Location2 {
            get {
                return ResourceManager.GetString("Location2", resourceCulture);
            }
        }
        
        internal static string Password2 {
            get {
                return ResourceManager.GetString("Password2", resourceCulture);
            }
        }
        
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        internal static string MsgMessageFlagSession {
            get {
                return ResourceManager.GetString("MsgMessageFlagSession", resourceCulture);
            }
        }
        
        internal static string MsgRequiresDestination2 {
            get {
                return ResourceManager.GetString("MsgRequiresDestination2", resourceCulture);
            }
        }
        
        internal static string MsgRequiresLocation2 {
            get {
                return ResourceManager.GetString("MsgRequiresLocation2", resourceCulture);
            }
        }
        
        internal static string MsgUnknownFormat {
            get {
                return ResourceManager.GetString("MsgUnknownFormat", resourceCulture);
            }
        }
        
        internal static string KeyType {
            get {
                return ResourceManager.GetString("KeyType", resourceCulture);
            }
        }
        
        internal static string MsgInvalidType {
            get {
                return ResourceManager.GetString("MsgInvalidType", resourceCulture);
            }
        }
        
        internal static string MsgMismatchedKind {
            get {
                return ResourceManager.GetString("MsgMismatchedKind", resourceCulture);
            }
        }
        
        internal static string MsgMismatchedType {
            get {
                return ResourceManager.GetString("MsgMismatchedType", resourceCulture);
            }
        }
        
        internal static string KeyTypes_Run_Encrypt_and_Decrypt_ {
            get {
                return ResourceManager.GetString("KeyTypes_Run_Encrypt_and_Decrypt_", resourceCulture);
            }
        }
        
        internal static string KeyTypes_Run___Symmetric_ {
            get {
                return ResourceManager.GetString("KeyTypes_Run___Symmetric_", resourceCulture);
            }
        }
        
        internal static string KeyTypes {
            get {
                return ResourceManager.GetString("KeyTypes", resourceCulture);
            }
        }
        
        internal static string KeyTypes_Unofficial {
            get {
                return ResourceManager.GetString("KeyTypes_Unofficial", resourceCulture);
            }
        }
        
        internal static string KeyTypes_Run___Asymmetric_ {
            get {
                return ResourceManager.GetString("KeyTypes_Run___Asymmetric_", resourceCulture);
            }
        }
        
        internal static string KeyTypes_Run____denotes_default_ {
            get {
                return ResourceManager.GetString("KeyTypes_Run____denotes_default_", resourceCulture);
            }
        }
        
        internal static string KeyTypes_Run_Sign_and_Verify_ {
            get {
                return ResourceManager.GetString("KeyTypes_Run_Sign_and_Verify_", resourceCulture);
            }
        }
        
        internal static string Pksc12Flag {
            get {
                return ResourceManager.GetString("Pksc12Flag", resourceCulture);
            }
        }
    }
}
