//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyczarTool {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localized {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localized() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeyczarTool.Localized", typeof(Localized).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new key to an existing key set..
        /// </summary>
        internal static string AddKey {
            get {
                return ResourceManager.GetString("AddKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use asymmetric algorithm (dsa|rsa)..
        /// </summary>
        internal static string Asymmetric {
            get {
                return ResourceManager.GetString("Asymmetric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use raw binary output..
        /// </summary>
        internal static string Binary {
            get {
                return ResourceManager.GetString("Binary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Compression (zlib|gzip)..
        /// </summary>
        internal static string Compression {
            get {
                return ResourceManager.GetString("Compression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new key set..
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location of the crypter key set to crypt the main key set..
        /// </summary>
        internal static string Crypter {
            get {
                return ResourceManager.GetString("Crypter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demote a given key version from the key set..
        /// </summary>
        internal static string Demote {
            get {
                return ResourceManager.GetString("Demote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination location of the operation..
        /// </summary>
        internal static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports primary private key to a PKCS Pem file..
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message is a file location..
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports a key into to an existing key set..
        /// </summary>
        internal static string ImportKey {
            get {
                return ResourceManager.GetString("ImportKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location of the import file..
        /// </summary>
        internal static string ImportLocation {
            get {
                return ResourceManager.GetString("ImportLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password for decrypting the imported key..
        /// </summary>
        internal static string ImportPassword {
            get {
                return ResourceManager.GetString("ImportPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location of the key set..
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message (uses std in if not set)..
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Password to PBE Keyset..
        /// </summary>
        internal static string MsgAddedPasssword {
            get {
                return ResourceManager.GetString("MsgAddedPasssword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed Password for PBE Keyset..
        /// </summary>
        internal static string MsgChangedPassword {
            get {
                return ResourceManager.GetString("MsgChangedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicting key types, {0} != {1}..
        /// </summary>
        internal static string MsgConflictingKeyTypes {
            get {
                return ResourceManager.GetString("MsgConflictingKeyTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not revoke Version:.
        /// </summary>
        internal static string MsgCouldNotRevoke {
            get {
                return ResourceManager.GetString("MsgCouldNotRevoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not write to:.
        /// </summary>
        internal static string MsgCouldNotWrite {
            get {
                return ResourceManager.GetString("MsgCouldNotWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created new key version:.
        /// </summary>
        internal static string MsgCreatedKey {
            get {
                return ResourceManager.GetString("MsgCreatedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Key set. .
        /// </summary>
        internal static string MsgCreatedKeySet {
            get {
                return ResourceManager.GetString("MsgCreatedKeySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demoted Version {0} to {1}..
        /// </summary>
        internal static string MsgDemotedVersion {
            get {
                return ResourceManager.GetString("MsgDemotedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not overwrite key set at:.
        /// </summary>
        internal static string MsgExistingKeySet {
            get {
                return ResourceManager.GetString("MsgExistingKeySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported to pem..
        /// </summary>
        internal static string MsgExportedPem {
            get {
                return ResourceManager.GetString("MsgExportedPem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For your export file,.
        /// </summary>
        internal static string MsgForExport {
            get {
                return ResourceManager.GetString("MsgForExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For your import file,.
        /// </summary>
        internal static string MsgForImport {
            get {
                return ResourceManager.GetString("MsgForImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For your key set,.
        /// </summary>
        internal static string MsgForKeySet {
            get {
                return ResourceManager.GetString("MsgForKeySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported new key version:.
        /// </summary>
        internal static string MsgImportedNewKey {
            get {
                return ResourceManager.GetString("MsgImportedNewKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid status:.
        /// </summary>
        internal static string MsgInvalidStatus {
            get {
                return ResourceManager.GetString("MsgInvalidStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;--message&apos; flag required with password..
        /// </summary>
        internal static string MsgMessageFlagWithPassword {
            get {
                return ResourceManager.GetString("MsgMessageFlagWithPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created new public keyset.
        /// </summary>
        internal static string MsgNewPublicKeySet {
            get {
                return ResourceManager.GetString("MsgNewPublicKeySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password didn&apos;t match..
        /// </summary>
        internal static string MsgPasswordDidNotMatch {
            get {
                return ResourceManager.GetString("MsgPasswordDidNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giving up..
        /// </summary>
        internal static string MsgPasswordGiveUp {
            get {
                return ResourceManager.GetString("MsgPasswordGiveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter password:.
        /// </summary>
        internal static string MsgPleaseEnterPassword {
            get {
                return ResourceManager.GetString("MsgPleaseEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please re-enter password:.
        /// </summary>
        internal static string MsgPleaseReenterPassword {
            get {
                return ResourceManager.GetString("MsgPleaseReenterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promoted Version {0} to {1}..
        /// </summary>
        internal static string MsgPromotedVersion {
            get {
                return ResourceManager.GetString("MsgPromotedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed the password from the keyset..
        /// </summary>
        internal static string MsgRemovedPassword {
            get {
                return ResourceManager.GetString("MsgRemovedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revoked Version..
        /// </summary>
        internal static string MsgRevokedVersion {
            get {
                return ResourceManager.GetString("MsgRevokedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Compression:.
        /// </summary>
        internal static string MsgUnknownCompression {
            get {
                return ResourceManager.GetString("MsgUnknownCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Version:.
        /// </summary>
        internal static string MsgUnknownVersion {
            get {
                return ResourceManager.GetString("MsgUnknownVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unparsable import file..
        /// </summary>
        internal static string MsgUnparsableImport {
            get {
                return ResourceManager.GetString("MsgUnparsableImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key set name..
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSA Padding (oaep|pkcs)..
        /// </summary>
        internal static string Padding {
            get {
                return ResourceManager.GetString("Padding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password for crypting the key set or crypter key set..
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds, changes, or removes password from PBE keyset..
        /// </summary>
        internal static string PasswordCommand {
            get {
                return ResourceManager.GetString("PasswordCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --New Password--.
        /// </summary>
        internal static string PasswordPromptNewPassword {
            get {
                return ResourceManager.GetString("PasswordPromptNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Old Password--.
        /// </summary>
        internal static string PasswordPromptOldPassword {
            get {
                return ResourceManager.GetString("PasswordPromptOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promote a given key version from the key set..
        /// </summary>
        internal static string Promote {
            get {
                return ResourceManager.GetString("Promote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracts public keys to a new key set..
        /// </summary>
        internal static string PubKey {
            get {
                return ResourceManager.GetString("PubKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The purpose of the key set (sign|crypt)..
        /// </summary>
        internal static string Purpose {
            get {
                return ResourceManager.GetString("Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove password from keyset..
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revoke a given key version from the key set..
        /// </summary>
        internal static string Revoke {
            get {
                return ResourceManager.GetString("Revoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key size in bits..
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The status (active|primary)..
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use unofficial key type (aes_aead)..
        /// </summary>
        internal static string UnofficialCreate {
            get {
                return ResourceManager.GetString("UnofficialCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses keyset to encrypt or sign a message..
        /// </summary>
        internal static string UseKey {
            get {
                return ResourceManager.GetString("UseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key version..
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
